### ISSUE TITLE
TypeError: can't pickle lxml.etree._Element objects

### ISSUE THREAD

**Issue by iamrishab** [elifesciences/sciencebeam-gym#229]
I am stuck at this error below while running `./preprocess.sh`. I have able to follow all the previous steps but i am not able to generate tfrecords properly for training. Below is the traceback of the error:

```

Traceback (most recent call last):
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rishab/repos/sciencebeam-gym/sciencebeam_gym/preprocess/preprocessing_pipeline.py", line 572, in <module>
    run()
  File "/home/rishab/repos/sciencebeam-gym/sciencebeam_gym/preprocess/preprocessing_pipeline.py", line 564, in run
    configure_pipeline(p, known_args)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/pipeline.py", line 547, in __exit__
    self.run().wait_until_finish()
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/pipeline.py", line 526, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/direct/direct_runner.py", line 130, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 173, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 183, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 331, in run_stages
    bundle_context_manager,
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 508, in _run_stage
    bundle_manager)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 546, in _run_bundle
    data_input, data_output, input_timers, expected_timer_output)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 930, in process_bundle
    timer_inputs)):
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/utils/thread_pool_executor.py", line 44, in run
    self._future.set_result(self._fn(*self._fn_args, **self._fn_kwargs))
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 926, in execute
    dry_run)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 826, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 353, in push
    response = self.worker.do_instruction(request)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 471, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 506, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 972, in process_bundle
    element.data)
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 218, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 330, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 332, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 963, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1030, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 961, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 553, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1122, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 963, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1030, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 961, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 553, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1122, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 963, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1030, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 961, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 553, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1122, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 963, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1030, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 961, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 553, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1122, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 963, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1030, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 961, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 553, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1122, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 138, in apache_beam.runners.worker.operations.ConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 963, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1045, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 961, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 553, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1122, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 194, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 164, in apache_beam.runners.worker.operations.ConsumerSet.update_counters_start
  File "apache_beam/runners/worker/opcounters.py", line 210, in apache_beam.runners.worker.opcounters.OperationCounters.update_from
  File "apache_beam/runners/worker/opcounters.py", line 230, in apache_beam.runners.worker.opcounters.OperationCounters.do_sample
  File "apache_beam/coders/coder_impl.py", line 1187, in apache_beam.coders.coder_impl.WindowedValueCoderImpl.get_estimated_size_and_observables
  File "apache_beam/coders/coder_impl.py", line 1198, in apache_beam.coders.coder_impl.WindowedValueCoderImpl.get_estimated_size_and_observables
  File "apache_beam/coders/coder_impl.py", line 386, in apache_beam.coders.coder_impl.FastPrimitivesCoderImpl.get_estimated_size_and_observables
  File "apache_beam/coders/coder_impl.py", line 433, in apache_beam.coders.coder_impl.FastPrimitivesCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 426, in apache_beam.coders.coder_impl.FastPrimitivesCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 442, in apache_beam.coders.coder_impl.FastPrimitivesCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 253, in apache_beam.coders.coder_impl.CallbackCoderImpl.encode_to_stream
  File "/home/rishab/anaconda3/envs/beam_env/lib/python3.6/site-packages/apache_beam/coders/coders.py", line 711, in <lambda>
    lambda x: dumps(x, HIGHEST_PROTOCOL), pickle.loads)
TypeError: can't pickle lxml.etree._Element objects [while running 'ConvertLxmlToSvgAndAnnotate/FlatMap(wrapper)']
```

Thanks in advance!

**Comment by de-code** [comment]
Hi, apologies, I only noticed your issue here.

One of the library upgrades probably broke it (I haven't run it myself for a while and it's obviously not covered the same by a test).
You could try to either downgrade some libraries (I suspect either `lxml` or `apache-beam`), or try to set `save_main_session` to `False` in `preprocessing_pipeline.py`.

**Comment by iamrishab** [comment]
Thank you for your inputs.

**Comment by sleepcoding3** [comment]
Hi, I am also facing the same issue. I could not resolve it either by downgrading `lxml` or `apache-beam` or by changing the `save_main_session` to `False`. From what I understand, pickling or unpickling `lxml.etree._Element` object resulting in error is a common bug, especially when done using multi-processing/multi-threading. And `apache-beam` use it in worker class so in multi-processing mode. Can anyone tell me how no one else faced this issue till now? Any other method to resolve it? What exactly happens when I change `save_main_session` to `False`? This is happening in main step of annotating the pdf files, so I cannot proceed further without resolving this.

Thank you in advance.

**Comment by de-code** [comment]
> What exactly happens when I change `save_main_session` to `False`?

By setting `save_main_session` to `False`, it should serialize less.

I believe the issue should be fixed now. You could try with the latest code.
